# Robot constants
PIPETTING_WELL_PROG = ""
PIPETTING_VIAL_PROG = ""

SWAP_WELL_LEFT = ""
SWAP_WELL_RIGHT = ""
SWAP_VIAL_LEFT = ""
SWAP_VIAL_RIGHT = ""

# XBOTS constants
PIPETTE_POSITION = []
WAIT_POSITION = []
SWAP_WELL_POSITION = []
SWAP_VIAL_POSITION = []
