# Robot constants
PIPETTING_WELL_PROG = ""
PIPETTING_VIAL_PROG = ""

SWAP_WELL_LEFT = ""
SWAP_WELL_RIGHT = ""
SWAP_VIAL_LEFT = ""
SWAP_VIAL_RIGHT = ""

# XBOTS constants
PIPETTE_POSITION = [0.840, 0.120]
WAIT_POSITION = [0.600, 0.120]
SWAP_WELL_POSITION = [0.120, 0.120]
SWAP_VIAL_POSITION = [0.360, 0.120]


# Positions for manual swap
X_PIPETTE = 0.840
X_WAIT = 0.600
Y_LOW = 0.060
Y_HIGH = 0.180

X_POS = [PIPETTE_POSITION[0],
         WAIT_POSITION[0],
         SWAP_WELL_POSITION[0],
         SWAP_VIAL_POSITION[0]]

Y_POS = [PIPETTE_POSITION[1],
         WAIT_POSITION[1],
         SWAP_WELL_POSITION[1],
         SWAP_VIAL_POSITION[1]]
